name: "Rohit Agarwal's Notes"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title.html
url: http://notes.rohitagarwal.org
author: Rohit Agarwal
description: "Hello, I am Rohit Agarwal. I am a software engineer. This is where I note my experiences while playing with new (and old) technologies."
gems:
  - jekyll-redirect-from
  - jekyll-gist
